### ISSUE TITLE
Birthday 3.5 interactive setup gives error Invalid Form Body

### ISSUE THREAD

**Issue by Skyridr** [Vexed01/Vex-Cogs#102]
### What cog is this bug report for?

Birthday

### What versions are you running?

```yes please
Versions                             
                ╷                        ╷         ╷              
                │ Current                │ Latest  │ Up to date?  
╶───────────────┼────────────────────────┼─────────┼─────────────╴
  This Cog      │ 1.1.1                  │ 1.1.1   │ 🟢           
  Bundled Utils │ 04f5f63                │ 04f5f63 │ 🟢           
  Red           │ 3.5.0.dev232+gcadcffba │ 3.4.18  │ 🟢           
                ╵                        ╵         ╵
```

### Describe the bug

Tried to check out the birthday cog on 3.5 dev, and noticed `bdset interactive` showing Interaction failed. With the console error shows below. I know 3.5 hasn't been fully released yet, and stuff can change all the time. But wanted to share it regardless, in case it wasn't known :). 

### If there's an error, paste it here

```python
Ignoring exception in view <SetupView timeout=180.0 children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Start setup' emoji=None row=None>:
Traceback (most recent call last):
  File "/home/redbot/lib/python3.9/site-packages/discord/ui/view.py", line 413, in _scheduled_task
    await item.callback(interaction)
  File "/home/redbot/cogs/CogManager/cogs/birthday/components/setup.py", line 23, in btn_start
    await interaction.response.send_modal(SetupModal(self.bot, self.config))
  File "/home/redbot/lib/python3.9/site-packages/discord/interactions.py", line 789, in send_modal
    await adapter.create_interaction_response(
  File "/home/redbot/lib/python3.9/site-packages/discord/webhook/async_.py", line 213, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.components.2.components.0: Value of field "type" must be one of (4,).
```
```

**Comment by Vexed01** [comment]
Thanks for reporting. I don't currently have a test 3.5 instance set up but I should be able to take a look before 3.5 is released
