### ISSUE TITLE
[StatTrack] SQLite column error

### ISSUE THREAD

**Issue by Vexed01** [Vexed01/Vex-Cogs#109]
### What cog is this bug report for?

StatTrack

### What versions are you running?

```yes please
Red 3.5 development version
Cog from red3.5 branch
```

### Describe the bug

Error report from Discord. Repeating here as otherwise I will forget about it (I already have for a couple months!).

https://discord.com/channels/240154543684321280/931931692619423805/1069207874435285023 from @japandotorg

This is not specific to the Red 3.5 branch.

### If there's an error, paste it here

```python
Exception in command 'stattrack channels'
Traceback (most recent call last):
  File "/root/env/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dpy2/cogs/CogManager/cogs/stattrack/commands.py", line 473, in channels
    await self.all_in_one(
  File "/data/dpy2/cogs/CogManager/cogs/stattrack/commands.py", line 47, in all_in_one
    df = await self.driver.read_partial([label] if isinstance(label, str) else label, delta)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dpy2/cogs/CogManager/cogs/stattrack/driver.py", line 85, in read_partial
    async with conn.execute(query) as cursor:
  File "/data/dpy2/cogs/Downloader/lib/aiosqlite/context.py", line 39, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "/data/dpy2/cogs/Downloader/lib/aiosqlite/core.py", line 192, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/dpy2/cogs/Downloader/lib/aiosqlite/core.py", line 137, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/data/dpy2/cogs/Downloader/lib/aiosqlite/core.py", line 110, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: no such column: channels_total

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/env/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1349, in invoke
    await ctx.command.invoke(ctx)
  File "/root/env/lib/python3.11/site-packages/redbot/core/commands/commands.py", line 782, in invoke
    await super().invoke(ctx)
  File "/root/env/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1642, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/env/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/env/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OperationalError: no such column: channels_total
```

**Comment by Vexed01** [comment]
After discussion in Discord neither of us can reproduce this error.
