### ISSUE TITLE
[Status] status.objects Error

### ISSUE THREAD

**Issue by Jac0bDan13L** [Vexed01/Vex-Cogs#16]
# Bug report

Cog failed to reload due to the following error after an update:

```py
Exception during loading of package
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 171, in _load
    await bot.load_extension(spec)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 1355, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/Red-DiscordBot/data/cybersafe/cogs/CogManager/cogs/status/__init__.py", line 3, in <module>
    from .core.status import Status
  File "/root/.local/share/Red-DiscordBot/data/cybersafe/cogs/CogManager/cogs/status/core/status.py", line 10, in <module>
    from ..commands.status_com import StatusCom
  File "/root/.local/share/Red-DiscordBot/data/cybersafe/cogs/CogManager/cogs/status/commands/status_com.py", line 11, in <module>
    from ..objects.caches import LastChecked, ServiceCooldown, ServiceRestrictionsCache
ModuleNotFoundError: No module named 'status.objects.caches'; 'status.objects' is not a package

```

**Comment by Vexed01** [comment]
Restarting your bot should fix this. Two people have now reported this, I'll put it in the changelog.

**Comment by Jac0bDan13L** [comment]
Restarting the bot does not fix this issue.

**Comment by Vexed01** [comment]
Ok, I guess it was a fluke that that fixed it for someone else. I am unable to reproduce this myself, I assume it's something to do with Downloader.

Try uninstalling the cog, removing my repo, adding my repo, then installing status again. And then if it still doesn't load, restart. That fixed it for someone else.

If this doesn't work please reach out to me in Discord as GitHub isn't the best place for this.
