### ISSUE TITLE
[Status] can't remove cloudflare

### ISSUE THREAD

**Issue by Technetium1** [Vexed01/Vex-Cogs#19]
```python
Traceback (most recent call last):
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/red/.local/share/Red-DiscordBot/data/TechBot/cogs/CogManager/cogs/status/commands/statusset_com.py", line 226, in statusset_remove
    sr[service.name].remove(channel.id)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/red/.pyenv/versions/red/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: list.remove(x): x not in list
```

```statusset remove cloudflare #coding``` was formatted correctly.

**Comment by Vexed01** [comment]
Interesting. Updates won't be sent anymore and I recommend running `[p]reload status` to reset the internal cache which looks like its what it was having trouble with.

I'll take a look at fixing this properly later today.

**Comment by Technetium1** [comment]
@Vexed01 It's very strange that it fixed with a reload! I restarted the bot multiple times over the last couple days with the same traceback before opening this issue. Feel free to close if/when needed.

**Comment by Technetium1** [comment]
![image](https://user-images.githubusercontent.com/9877150/116510139-706fd180-a892-11eb-84d5-bfe2898702eb.png)

Got a new traceback for you.

**Comment by Vexed01** [comment]
Yeah... I see what the issue is but idk what caused it to not be in the restrictions cache/config.

Thanks for the new traceback, I'll try to take a look at it later today.

**Comment by Vexed01** [comment]
Do you have an idea when you added Cloudflare to that channel?

I'm thinking it might be some broken migration.

**Comment by Technetium1** [comment]
The first time I used cloudflare was on the 24th. Sorry for the poor quality screenshot
![image](https://user-images.githubusercontent.com/9877150/116511780-f7be4480-a894-11eb-8f2f-f73cf8036c46.png)

**Comment by Vexed01** [comment]
Ok, this should now be fixed if you update. Thanks for letting me know!

**Comment by Technetium1** [comment]
Confirming this is fixed :)
